[Quantum RPG] Add help and descriptions to qaracter actions
quantumlib/unitary pull request #111
Opened 2023-07-02 01:33 UTC by dstrain115

Now, the qaracter actions are explained, such as:
`s) Sample enemy qubit.`

There is also a help option within the battle.

2023-07-04 23:18 UTC, cognigami requested changes

2023-07-04 23:18 UTC, cognigami commented on unitary/examples/quantum_rpg/battle_test.py
> +amplitude. Try to measure the enemy qubits as |0> to defwat them.
defwat
defeat

2023-07-04 23:18 UTC, cognigami commented on unitary/examples/quantum_rpg/classes.py
> +            "The Engineer can 'attack' by applying an X gate to an enemw'y qubit.\n"
enemw'y
enemy

2023-07-04 23:18 UTC, cognigami commented on unitary/examples/quantum_rpg/classes.py
> +        msg += "amplitude. Try to measure the enemy qubits as |0> to defwat them.\n"
defwat
defeat

2023-07-05 13:57 UTC, cognigami approved these changes

2023-07-05 13:58 UTC, dstrain115 commented on unitary/examples/quantum_rpg/classes.py
> +        msg += "amplitude. Try to measure the enemy qubits as |0> to defwat them.\n"
Done.

2023-07-05 13:58 UTC, dstrain115 commented on unitary/examples/quantum_rpg/classes.py
> +            "The Engineer can 'attack' by applying an X gate to an enemw'y qubit.\n"
Done.

2023-07-05 13:58 UTC, dstrain115 commented on unitary/examples/quantum_rpg/battle_test.py
> +amplitude. Try to measure the enemy qubits as |0> to defwat them.
Done.

2023-07-05 14:05 UTC, merged