[Quantum RPG] Add information on how to play
quantumlib/unitary pull request #142
Opened 2023-07-30 01:52 UTC by dstrain115

- Add more to the README about how to install and play the game.

2023-07-31 17:02 UTC, cognigami requested changes

2023-07-31 17:02 UTC, cognigami commented on unitary/examples/quantum_rpg/README.md
> +they are **DOWN**.  If half or more are measured in the one state, they are
DEL are
REPLACE one
WITH 1

2023-07-31 17:02 UTC, cognigami commented on unitary/examples/quantum_rpg/README.md
> +Once a character (or enemy) has measured half or more qubits in the zero state,
REPLACE zero
WITH 0

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +onto the circuit or measure the circuit.  The goal will be for the
Done.

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +Each character and adversary will have actions that can modify (append)
Done.

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +
Done.

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +(you may need to make sure that the unitary library is in your PYTHONPATH).
Done.

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +Once a character (or enemy) has measured half or more qubits in the zero state,
Replaced with |0>

2023-07-31 21:24 UTC, dstrain115 commented on unitary/examples/quantum_rpg/README.md
> +they are **DOWN**.  If half or more are measured in the one state, they are
Changed to |1>

2023-08-01 16:11 UTC, cognigami approved these changes

2023-08-01 16:20 UTC, merged