Create overview.md
quantumlib/unitary pull request #152
Opened 2023-09-08 11:53 UTC by dstrain115

Create the overview of unitary from the document created by @cognigami

2023-09-11 15:57 UTC, cognigami requested changes

2023-09-11 15:57 UTC, cognigami commented on docs/unitary/overview.md
> +## Sampler
Remove space.

2023-09-13 14:17 UTC, dstrain115 commented on docs/unitary/overview.md
> +## Measurement
I actually did the opposite and added spaces where they wer missing above.  The extra space is needed for markdown to denote a title style.

2023-09-13 14:17 UTC, dstrain115 commented on docs/unitary/overview.md
> +## Quantum state and classical state
Same

2023-09-13 14:17 UTC, dstrain115 commented on docs/unitary/overview.md
> +## Sampler
Same.

2023-09-15 21:30 UTC, cognigami approved these changes

2023-09-15 21:40 UTC, merged