[Unitary[ Create game_design.md
quantumlib/unitary pull request #154
Opened 2023-09-08 12:21 UTC by dstrain115

2023-09-11 15:59 UTC, cognigami requested changes

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +# Game Design
Remove space between # and Game.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## State
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Entanglement
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Interference
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Measurement
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Simplicity
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Composability
Remove space.

2023-09-11 15:59 UTC, cognigami commented on docs/unitary/game_design.md
> +## Example: Quantum Chess
Remove space.

2023-09-13 14:12 UTC, dstrain115 commented on docs/unitary/game_design.md
> +## Entanglement
Same.

2023-09-13 14:12 UTC, dstrain115 commented on docs/unitary/game_design.md
> +## Measurement
Same.

2023-09-13 14:12 UTC, dstrain115 commented on docs/unitary/game_design.md
> +## Simplicity
Same.

2023-09-13 14:12 UTC, dstrain115 commented on docs/unitary/game_design.md
> +## Composability
Same.

2023-09-13 14:12 UTC, dstrain115 commented on docs/unitary/game_design.md
> +## Example: Quantum Chess
Same.

2023-09-15 21:31 UTC, cognigami approved these changes

2023-09-15 21:39 UTC, merged